# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: serv_proto.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='serv_proto.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x10serv_proto.proto\"I\n\x10\x43\x61lculateMessage\x12\x11\n\tOperation\x18\x01 \x01(\t\x12\x10\n\x08Operand1\x18\x02 \x01(\x01\x12\x10\n\x08Operand2\x18\x03 \x01(\x01\"#\n\x11\x43\x61lculatedMessage\x12\x0e\n\x06result\x18\x01 \x01(\x01*/\n\tOperation\x12\x07\n\x03MUL\x10\x00\x12\x07\n\x03\x44IV\x10\x01\x12\x07\n\x03SUB\x10\x02\x12\x07\n\x03SUM\x10\x03\x32\x42\n\nCalculator\x12\x34\n\tCalculate\x12\x11.CalculateMessage\x1a\x12.CalculatedMessage\"\x00\x62\x06proto3'
)

_OPERATION = _descriptor.EnumDescriptor(
  name='Operation',
  full_name='Operation',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='MUL', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='DIV', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='SUB', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='SUM', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=132,
  serialized_end=179,
)
_sym_db.RegisterEnumDescriptor(_OPERATION)

Operation = enum_type_wrapper.EnumTypeWrapper(_OPERATION)
MUL = 0
DIV = 1
SUB = 2
SUM = 3



_CALCULATEMESSAGE = _descriptor.Descriptor(
  name='CalculateMessage',
  full_name='CalculateMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='Operation', full_name='CalculateMessage.Operation', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Operand1', full_name='CalculateMessage.Operand1', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Operand2', full_name='CalculateMessage.Operand2', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=20,
  serialized_end=93,
)


_CALCULATEDMESSAGE = _descriptor.Descriptor(
  name='CalculatedMessage',
  full_name='CalculatedMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='CalculatedMessage.result', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=95,
  serialized_end=130,
)

DESCRIPTOR.message_types_by_name['CalculateMessage'] = _CALCULATEMESSAGE
DESCRIPTOR.message_types_by_name['CalculatedMessage'] = _CALCULATEDMESSAGE
DESCRIPTOR.enum_types_by_name['Operation'] = _OPERATION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CalculateMessage = _reflection.GeneratedProtocolMessageType('CalculateMessage', (_message.Message,), {
  'DESCRIPTOR' : _CALCULATEMESSAGE,
  '__module__' : 'serv_proto_pb2'
  # @@protoc_insertion_point(class_scope:CalculateMessage)
  })
_sym_db.RegisterMessage(CalculateMessage)

CalculatedMessage = _reflection.GeneratedProtocolMessageType('CalculatedMessage', (_message.Message,), {
  'DESCRIPTOR' : _CALCULATEDMESSAGE,
  '__module__' : 'serv_proto_pb2'
  # @@protoc_insertion_point(class_scope:CalculatedMessage)
  })
_sym_db.RegisterMessage(CalculatedMessage)



_CALCULATOR = _descriptor.ServiceDescriptor(
  name='Calculator',
  full_name='Calculator',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=181,
  serialized_end=247,
  methods=[
  _descriptor.MethodDescriptor(
    name='Calculate',
    full_name='Calculator.Calculate',
    index=0,
    containing_service=None,
    input_type=_CALCULATEMESSAGE,
    output_type=_CALCULATEDMESSAGE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_CALCULATOR)

DESCRIPTOR.services_by_name['Calculator'] = _CALCULATOR

# @@protoc_insertion_point(module_scope)
